language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
env:
  - DJANGO=django==1.4.10
  - DJANGO=django==1.5.5
  - DJANGO=django==1.6
  - DJANGO=django==1.6 DB_ENGINE="django.db.backends.postgresql_psycopg2" DB_NAME="test_project" DB_USER="postgres"
  - DJANGO=django==1.6 DB_ENGINE="django.db.backends.mysql" DB_NAME="test_project" DB_USER="travis"
matrix:
  exclude:
    - python: 3.2
      env: DJANGO=django==1.4.10
    - python: 3.3
      env: DJANGO=django==1.4.10
services:
  - postgresql
  - mysql
install:
  - pip install $DJANGO psycopg2 MySQL-python
  - python setup.py -q install
before_script:
  - mysql -e 'create database test_project'
  - psql -c 'create database test_project;' -U postgres
script: python src/test_project/manage.py test watson
notifications:
  email: false


